config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login' => "sessions#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'message' => 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body , presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true,

            uniqueness: { case_sensitive: false },

            length: { minimum: 3, maximum: 25 }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user , :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform this action"
      redirect_to login_path
    end
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new()
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial:'message', locals: {message:message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if(user && user.authenticate(params[:session][:password]))
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully."
      redirect_to root_path
    else
      flash.now[:error] = "There was something wrong with login credentials."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui inverted segment center aligned medium icon header">
  <i class="circular coffee icon inverted teal"></i>
  Say Something
</h2>

<div class="ui grid">

  <div class="twelve wide column">

    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">

     <div class="ui inverted small feed" id="message-container">
       <h4 class="ui header">Followers Activity</h4>

       <%= render @messages  %>

     </div>
      </div>

      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path , remote: true) do |s| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= s.text_field :body , placeholder: "Enter a Message.." %>
              <%= s.button '<i class="bordered inverted edit icon circular"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
    <div class="ui inverted vertical menu">
     <a class="active item">
       Home
     </a>
      <a class="item">
       Messages
      </a>
  <a class="item">
    Friends
  </a>
</div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright to Legacy .Inc &copy;
      Built by Prasad Zore.
    </small>
    <nav>
      <ul>
        <li>
          <h5> Welcome</h5>
        </li>
      </ul>
    </nav>
  </footer>

</div>

app/views/layouts/_menubar.html.erb
<div class="ui inverted small menu segment">
  <div class="ui container">
    <%= link_to "Chatroom", root_path ,class:"item" %>
  <a class="item">
    Messages
  </a>
  <div class="right menu">
    <div class="ui dropdown item">
      Account <i class="dropdown icon"></i>
      <div class="menu">
        <% if logged_in? %>
            <%= link_to "Log Out", logout_path , method: :delete , class:"item" %>
        <% else %>
            <%= link_to "Log In", login_path , class:"item" %>
            <a class="item">Sign Up</a>
        <% end %>
      </div>
    </div>
    <div class="item">
      <div class="ui primary button">Sign Up</div>
    </div>
  </div>

  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/menubar' %>
    <div class="ui container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em> <%= message.user.username %> </em>: <%= message.body %>
    </div>
  </div>
</div>